import { TransactionFormState } from "../reducers/transaction-form-reducer";
import { BusinessLoan } from "./business-loan-requests";
import { TransactionReturnInfo } from "./transaction-requests";
import { Wallet } from "./wallet-requests";

export const connectUrl:string = "http://13.57.199.209";

export const businessForm:string = `{
    "address":"",
    "email":"",
    "name":"",
    "password":"",
    "phoneNumber":0,
    "username":"",
    "bin":0,
    "ein":0
}` 

export const businessFormDef:string = `{
    "newBusiness":{
        "address":"Type address here",
        "email":"example@example.com",
        "name":"Type name here",
        "password":"Secret Password",
        "phoneNumber":4062539687,
        "username":"Alias for account",
        "bin":0,
        "ein":0
    }
}`

export const businessUpdateDef:string=`{
    "updateBusinessDetails":{
        
        "bin":0,
        "ein":0
    }
}`
// Generated by https://quicktype.io

export type BusinessEntity = {
    address:             string;
    email:               string;
    businessAccount: boolean;
    name:                string;
    password:            string;
    phone_number:        number;
    username:            string;
    bin:                 number;
    ein:                 number;
    isForProfit:       boolean;
}

export type BusinessForm = {
    address:             string;
    email:               string;
    name:                string;
    password:            string;
    phoneNumber:        number;
    username:            string;
    bin:                 number;
    ein:                 number;
}

export type CompState={
    id:number 
    checked:boolean
    about:string
}

export type CompsCheckedState={
    compsChecked:CompState[]
}

export type UserAccount={
    accountId:number
    username:string
    password:string
    email:string
    phoneNumber:number
    name:string
    address:string
    businessAccount:boolean
}

export type BusinessAccount={
    accountId:number
    username:string
    password:string
    email:string
    phoneNumber:number
    name:string
    address:string
    businessAccount:boolean
    businessId:number
}

export type BusinessDetails={
    businessId:number
    bin:number
    ein:number
    forProfit:boolean
    accountId:number
}

export type Card = {
    cardNumber: number
    accountId: number
    credit: boolean
}


export type BusinessInfo = {
    businessId:          number;
    accountId:           number;
    address:             string;
    email:               string;
    businessAccount: boolean;
    name:                string;
    phone_number:        number;
    username:            string;
    bin:                 number;
    ein:                 number;
    forProfit:       boolean;
    wallet:             Wallet;
    transactions:  TransactionReturnInfo[];
    loans:          BusinessLoan[];
}

