export const businessForm:string = `{
    "address":"",
    "email":"",
    "name":"",
    "password":"",
    "phoneNumber":0,
    "username":"",
    "bin":0,
    "ein":0
}` 

export const businessFormDef:string = `{
    "newBusiness":{
        "address":"Type address here",
        "email":"example@example.com",
        "name":"Type name here",
        "password":"Secret Password",
        "phoneNumber":4062539687,
        "username":"Alias for account",
        "bin":0,
        "ein":0
    }
}`

// Generated by https://quicktype.io

export type BusinessEntity = {
    address:             string;
    email:               string;
    isBusinessAccount: boolean;
    name:                string;
    password:            string;
    phone_number:        number;
    username:            string;
    bin:                 number;
    ein:                 number;
    isForProfit:       boolean;
}

export type BusinessForm = {
    address:             string;
    email:               string;
    name:                string;
    password:            string;
    phoneNumber:        number;
    username:            string;
    bin:                 number;
    ein:                 number;
}

export type CompState={
    id:number 
    checked:boolean
    about:string
}

export type CompsCheckedState={
    compsChecked:CompState[]
}

export type UserAccount={
    accountId:number
    username:string
    password:string
    email:string
    phoneNumber:number
    name:string
    address:string
    isBusinessAccount:boolean
}

export type BusinessDetails={
    businessId:number
    bin:number
    ein:number
    isForProfit:boolean
    accountId:number
}